name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown

      - name: Install cargo-binstall
        run: cargo install cargo-binstall

      - name: Install cargo-leptos
        run: cargo binstall cargo-leptos

      - name: Build
        run: |
          cd ldtatkinson
          cargo leptos build --release
          cp index.html target/site/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ldtatkinson/target/site
